#!/bin/sh
#
# bookclubbot Starts/stops BookClubBot
#
# chkconfig:   345 95 5
# description: Runs the Discord bot program BookClubBot.

### BEGIN INIT INFO
# Provides: bookclubbot
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Default-Start: 345
# Default-Stop: 95
# Short-Description: Starts/stops BookClubBot
# Description:      Runs the Discord bot program BookClubBot.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog="bookclubbot"
progdir="/usr/local/src/$prog"
logfile="/var/log/$prog/$prog.log"
pidfile="/var/run/$prog/$prog.pid"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    echo -n $"Starting $prog: "
    /usr/bin/python3 $progdir/bookclub_bot.py \
      --user $USER --group $GROUP \
      --logfile "$logfile" --pidfile "$pidfile" \
      --devmode "$DEVMODE" \
      --emailfrom "$EMAILFROM" --emailto "$EMAILTO" \
      --emailsubject "$EMAILSUBJECT" \
      --dbuser "$DBUSER" --dbpassword "$DBPASSWORD" \
      --dbhost "$DBHOST" --db "$DB" \
      "$TOKEN"
    retval=$?
    if [ $retval -eq 0 ]; then
      touch $lockfile
      success
    else
      failure
    fi
    echo
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile -d 10 $prog
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f $lockfile
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
